export const commandIds: readonly string[] = [
  'acceptInput',
  'focus',
  'focusFirst',
  'handleFocus',
  'focusIndex',
  'focusLast',
  'focusNext',
  'focusNone',
  'focusPrevious',
  'handleClick',
  'handleClickAt',
  'selectIndex',
  'handleIconThemeChange',
  'handleWheel',
]
