import type { SourceControlState } from '../SourceControlState/SourceControlState.ts'

export const createDefaultState = (): SourceControlState => ({
  actionsCache: Object.create(null),
  allGroups: [],
  deltaY: 0,
  enabledProviderIds: [],
  fileIconCache: {},
  finalDeltaY: 0,
  gitRoot: '',
  handleOffset: 0,
  headerHeight: 40,
  height: 100,
  id: 1,
  index: [],
  inputValue: '',
  expandedGroups: Object.create(null),
  itemHeight: 20,
  items: [],
  maxLineY: 0,
  merge: [],
  minimumSliderSize: 30,
  minLineY: 0,
  providerId: '',
  root: '/',
  scrollBarActive: false,
  scrollBarHeight: 0,
  splitButtonEnabled: false,
  untracked: [],
  visibleItems: [],
  width: 100,
  workingTree: [],
  workspacePath: '',
  x: 0,
  y: 0,
  inputPlaceholder: '',
  inputSource: 0,
})
