import type { SourceControlState } from '../SourceControlState/SourceControlState.ts'

export const createDefaultState = (): SourceControlState => ({
  allGroups: [],
  buttonIndex: 0,
  buttons: [],
  deltaY: 0,
  enabledProviderIds: [],
  fileIconCache: {},
  finalDeltaY: 0,
  gitRoot: '',
  handleOffset: 0,
  height: 100,
  icons: [],
  id: 1,
  index: [],
  inputValue: '',
  isExpanded: false,
  itemHeight: 20,
  items: [],
  maxLineY: 0,
  merge: [],
  minimumSliderSize: 30,
  minLineY: 0,
  providerId: '',
  root: '/',
  scrollBarActive: false,
  scrollBarHeight: 0,
  splitButtonEnabled: false,
  untracked: [],
  width: 100,
  workingTree: [],
  workspacePath: '',
  x: 0,
  y: 0,
  headerHeight: 40,
  actionsCache: Object.create(null),
})
