name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        attempt: [1, 2, 3, 4]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node packages/build/src/computeNodeModulesCacheKey.ts)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v6
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run build
      - run: npm run build:static
      - run: npm test
      - run: npm run test-integration
      - run: npm run type-check
      - run: npm run lint
      - name: install playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install chromium
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: e2e
        working-directory: ./packages/e2e
        run: npm run e2e:headless -- --filter=source-control.input-actions 2>&1 | tee e2e.log
        shell: bash
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: e2e-${{ matrix.attempt }}
          path: packages/e2e/e2e.log
          if-no-files-found: ignore
